CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "cargo_id" int NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_en" timestamp,
  "eliminado_en" timestamp
);

CREATE TABLE "tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "jti" varchar(255) UNIQUE NOT NULL,
  "issued_at" timestamp DEFAULT (now()),
  "expires_at" timestamp NOT NULL,
  "revoked_at" timestamp,
  "reason" varchar(255),
  "active" boolean DEFAULT true
);

CREATE TABLE "cargo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "nivel" int NOT NULL,
  "creado_por" int,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp,
  "eliminado_en" timestamp
);

CREATE TABLE "maquina" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "creado_por" int,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp,
  "eliminado_en" timestamp
);

CREATE TABLE "template" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp,
  "eliminado_por" int,
  "eliminado_en" timestamp
);

CREATE TABLE "template_seccion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(250) NOT NULL,
  "template_id" int NOT NULL,
  "orden" smallint NOT NULL,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp,
  "eliminado_por" int,
  "eliminado_en" timestamp
);

CREATE TABLE "inspeccion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_inicio" timestamp NOT NULL,
  "fecha_finalizacion" timestamp,
  "maquina_id" int NOT NULL,
  "num_serie" varchar(50) UNIQUE NOT NULL,
  "n_serie_motor" varchar(50),
  "cabinado" boolean,
  "horometro" decimal(10,2),
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp,
  "eliminado_por" int,
  "eliminado_en" timestamp
);

CREATE TABLE "eleccion_template" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_id" int NOT NULL,
  "inspeccion_id" bigint NOT NULL,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp
);

CREATE TABLE "resultado_atributo_checklist" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cumple" boolean,
  "observacion_id" bigint,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp
);

CREATE TABLE "eleccion_respuesta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "eleccion_template_id" int NOT NULL,
  "template_seccion_id" int NOT NULL,
  "resultado_atributo_checklist_id" bigint NOT NULL,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp
);

CREATE TABLE "rol_asignacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "creado_por" int,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp,
  "eliminado_en" timestamp
);

CREATE TABLE "asignacion_inspeccion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inspeccion_id" bigint NOT NULL,
  "usuario_id" int NOT NULL,
  "rol_asignacion_id" int NOT NULL,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp
);

CREATE TABLE "observacion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text NOT NULL,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp
);

CREATE TABLE "archivo" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "tamano" bigint NOT NULL,
  "ruta" varchar(500),
  "url" varchar(1000),
  "categoria" varchar(50) NOT NULL,
  "hash" char(64) UNIQUE NOT NULL,
  "observacion_id" bigint,
  "creado_por" int NOT NULL,
  "creado_en" timestamp DEFAULT (now()),
  "actualizado_por" int,
  "actualizado_en" timestamp
);

CREATE TABLE "auditoria_operacion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tabla_afectada" varchar(50) NOT NULL,
  "id_registro" bigint NOT NULL,
  "operacion" varchar(10) NOT NULL,
  "usuario_id" int NOT NULL,
  "fecha_operacion" timestamp DEFAULT (now())
);

CREATE TABLE "auditoria_detalle" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auditoria_operacion_id" bigint NOT NULL,
  "campo_modificado" varchar(100) NOT NULL,
  "valor_anterior" text,
  "valor_nuevo" text,
  "tipo_dato" varchar(20) NOT NULL
);

CREATE INDEX ON "usuario" ("cargo_id");

CREATE INDEX ON "usuario" ("correo");

CREATE INDEX ON "usuario" ("eliminado_en");

CREATE UNIQUE INDEX "idx_tokens_jti" ON "tokens" ("jti");

CREATE INDEX "idx_tokens_user_active" ON "tokens" ("user_id", "active");

CREATE INDEX "idx_tokens_expires" ON "tokens" ("expires_at");

CREATE INDEX ON "cargo" ("eliminado_en");

CREATE INDEX ON "maquina" ("eliminado_en");

CREATE INDEX ON "template" ("eliminado_en");

CREATE INDEX ON "template_seccion" ("template_id");

CREATE UNIQUE INDEX "idx_template_seccion_orden_unico" ON "template_seccion" ("template_id", "orden", "eliminado_en");

CREATE INDEX ON "template_seccion" ("eliminado_en");

CREATE INDEX ON "inspeccion" ("maquina_id");

CREATE INDEX ON "inspeccion" ("fecha_inicio");

CREATE INDEX ON "inspeccion" ("fecha_finalizacion");

CREATE INDEX ON "inspeccion" ("eliminado_en");

CREATE INDEX ON "inspeccion" ("maquina_id", "fecha_inicio");

CREATE INDEX ON "eleccion_template" ("inspeccion_id");

CREATE INDEX ON "eleccion_template" ("template_id");

CREATE UNIQUE INDEX "idx_eleccion_template_unica" ON "eleccion_template" ("inspeccion_id", "template_id");

CREATE INDEX ON "resultado_atributo_checklist" ("observacion_id");

CREATE INDEX ON "resultado_atributo_checklist" ("creado_por");

CREATE INDEX ON "resultado_atributo_checklist" ("creado_en");

CREATE INDEX ON "eleccion_respuesta" ("eleccion_template_id");

CREATE INDEX ON "eleccion_respuesta" ("template_seccion_id");

CREATE INDEX ON "eleccion_respuesta" ("resultado_atributo_checklist_id");

CREATE UNIQUE INDEX "idx_respuesta_unica_por_atributo" ON "eleccion_respuesta" ("eleccion_template_id", "template_seccion_id");

CREATE INDEX ON "rol_asignacion" ("eliminado_en");

CREATE INDEX ON "asignacion_inspeccion" ("inspeccion_id");

CREATE INDEX ON "asignacion_inspeccion" ("usuario_id");

CREATE INDEX ON "asignacion_inspeccion" ("rol_asignacion_id");

CREATE UNIQUE INDEX "idx_usuario_unico_por_inspeccion" ON "asignacion_inspeccion" ("inspeccion_id", "usuario_id");

CREATE INDEX ON "observacion" ("creado_por");

CREATE INDEX ON "observacion" ("creado_en");

CREATE INDEX ON "archivo" ("observacion_id");

CREATE INDEX ON "archivo" ("hash");

CREATE INDEX ON "archivo" ("creado_por");

CREATE INDEX ON "archivo" ("categoria");

CREATE INDEX ON "auditoria_operacion" ("usuario_id");

CREATE INDEX ON "auditoria_operacion" ("tabla_afectada", "id_registro");

CREATE INDEX ON "auditoria_operacion" ("fecha_operacion");

CREATE INDEX ON "auditoria_operacion" ("fecha_operacion", "tabla_afectada");

CREATE INDEX ON "auditoria_detalle" ("auditoria_operacion_id");

CREATE INDEX "idx_auditoria_detalle_campo" ON "auditoria_detalle" ("auditoria_operacion_id", "campo_modificado");

COMMENT ON TABLE "tokens" IS 'Gestión de tokens JWT con auditoría de sesiones
BigInt para alto volumen diario de logins
Limpieza automática: DELETE FROM tokens WHERE expires_at < NOW() - INTERVAL ''30 days''
';

COMMENT ON COLUMN "maquina"."nombre" IS 'Modelo';

COMMENT ON TABLE "template" IS 'Checklist - Ejemplo: "REVISIÓN PUESTA EN MARCHA, REGULACIONES Y MOVIMIENTOS"';

COMMENT ON TABLE "template_seccion" IS 'Un template puede tener múltiples secciones/atributos
El orden define la secuencia de visualización en el checklist
La constraint única permite reutilizar órdenes de secciones eliminadas
';

COMMENT ON COLUMN "template_seccion"."orden" IS 'Orden de visualización (1-32767)';

COMMENT ON TABLE "inspeccion" IS 'Representa una inspección de maquinaria
CHECK: fecha_finalizacion IS NULL OR fecha_finalizacion >= fecha_inicio
Implementar en BD: ALTER TABLE inspeccion ADD CONSTRAINT chk_fechas_validas CHECK (fecha_finalizacion IS NULL OR fecha_finalizacion >= fecha_inicio)
';

COMMENT ON COLUMN "inspeccion"."fecha_finalizacion" IS 'NULL si aún está en proceso';

COMMENT ON COLUMN "inspeccion"."horometro" IS 'Horas de uso';

COMMENT ON TABLE "eleccion_template" IS 'Una inspección puede usar múltiples templates (checklists)
Pero no puede repetir el mismo template
La constraint única previene duplicados considerando soft delete
';

COMMENT ON TABLE "resultado_atributo_checklist" IS 'Resultado de verificación: Sí/No/N/A';

COMMENT ON COLUMN "resultado_atributo_checklist"."cumple" IS 'true=Sí, false=No, NULL=N/A';

COMMENT ON COLUMN "resultado_atributo_checklist"."creado_por" IS 'Quien verificó este parámetro';

COMMENT ON TABLE "eleccion_respuesta" IS 'Cada atributo (template_seccion) de un checklist solo puede responderse una vez por inspección
La constraint única asegura que no se dupliquen respuestas para el mismo atributo
Flujo: eleccion_template define qué checklist → template_seccion son los atributos → resultado es la respuesta
';

COMMENT ON COLUMN "eleccion_respuesta"."eleccion_template_id" IS 'Qué checklist de la inspección';

COMMENT ON COLUMN "eleccion_respuesta"."template_seccion_id" IS 'Qué atributo se está respondiendo';

COMMENT ON COLUMN "eleccion_respuesta"."resultado_atributo_checklist_id" IS 'La respuesta: Sí/No/N/A';

COMMENT ON TABLE "asignacion_inspeccion" IS 'Un usuario solo puede tener un rol activo por inspección
Si se necesita cambiar el rol, se elimina lógicamente el anterior y se crea uno nuevo
';

COMMENT ON TABLE "archivo" IS 'Almacenamiento flexible de archivos:
- Archivo local: ruta NOT NULL, url NULL
- URL externa: url NOT NULL, ruta NULL
- Validación a nivel de aplicación: al menos uno debe existir
';

COMMENT ON COLUMN "archivo"."tamano" IS 'Tamaño en bytes (0 si es URL externa)';

COMMENT ON COLUMN "archivo"."ruta" IS 'Ruta del archivo en disco (NULL si es URL externa)';

COMMENT ON COLUMN "archivo"."url" IS 'URL pública del archivo (NULL si es archivo local)';

COMMENT ON COLUMN "archivo"."categoria" IS 'Categoría: imagen, documento, pdf, video, etc.';

COMMENT ON COLUMN "archivo"."hash" IS 'SHA-256 para deduplicación (hash del contenido o de la URL)';

COMMENT ON TABLE "auditoria_operacion" IS 'Auditoría centralizada de todas las operaciones
Considerar particionamiento por fecha para tablas grandes
Implementar política de retención (ej: 2 años)
';

COMMENT ON COLUMN "auditoria_operacion"."operacion" IS 'INSERT, UPDATE, DELETE';

ALTER TABLE "usuario" ADD FOREIGN KEY ("cargo_id") REFERENCES "cargo" ("id");

ALTER TABLE "tokens" ADD FOREIGN KEY ("user_id") REFERENCES "usuario" ("id");

ALTER TABLE "cargo" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "cargo" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "maquina" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "maquina" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "template" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "template" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "template" ADD FOREIGN KEY ("eliminado_por") REFERENCES "usuario" ("id");

ALTER TABLE "template_seccion" ADD FOREIGN KEY ("template_id") REFERENCES "template" ("id");

ALTER TABLE "template_seccion" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "template_seccion" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "template_seccion" ADD FOREIGN KEY ("eliminado_por") REFERENCES "usuario" ("id");

ALTER TABLE "inspeccion" ADD FOREIGN KEY ("maquina_id") REFERENCES "maquina" ("id");

ALTER TABLE "inspeccion" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "inspeccion" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "inspeccion" ADD FOREIGN KEY ("eliminado_por") REFERENCES "usuario" ("id");

ALTER TABLE "eleccion_template" ADD FOREIGN KEY ("template_id") REFERENCES "template" ("id");

ALTER TABLE "eleccion_template" ADD FOREIGN KEY ("inspeccion_id") REFERENCES "inspeccion" ("id");

ALTER TABLE "eleccion_template" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "eleccion_template" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "resultado_atributo_checklist" ADD FOREIGN KEY ("observacion_id") REFERENCES "observacion" ("id");

ALTER TABLE "resultado_atributo_checklist" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "resultado_atributo_checklist" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "eleccion_respuesta" ADD FOREIGN KEY ("eleccion_template_id") REFERENCES "eleccion_template" ("id");

ALTER TABLE "eleccion_respuesta" ADD FOREIGN KEY ("template_seccion_id") REFERENCES "template_seccion" ("id");

ALTER TABLE "eleccion_respuesta" ADD FOREIGN KEY ("resultado_atributo_checklist_id") REFERENCES "resultado_atributo_checklist" ("id");

ALTER TABLE "eleccion_respuesta" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "eleccion_respuesta" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "rol_asignacion" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "rol_asignacion" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "asignacion_inspeccion" ADD FOREIGN KEY ("inspeccion_id") REFERENCES "inspeccion" ("id");

ALTER TABLE "asignacion_inspeccion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "asignacion_inspeccion" ADD FOREIGN KEY ("rol_asignacion_id") REFERENCES "rol_asignacion" ("id");

ALTER TABLE "asignacion_inspeccion" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "asignacion_inspeccion" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "observacion" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "observacion" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "archivo" ADD FOREIGN KEY ("observacion_id") REFERENCES "observacion" ("id");

ALTER TABLE "archivo" ADD FOREIGN KEY ("creado_por") REFERENCES "usuario" ("id");

ALTER TABLE "archivo" ADD FOREIGN KEY ("actualizado_por") REFERENCES "usuario" ("id");

ALTER TABLE "auditoria_operacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "auditoria_detalle" ADD FOREIGN KEY ("auditoria_operacion_id") REFERENCES "auditoria_operacion" ("id");
